language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  # - pip install .
# command to run tests
script:
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py test
# Push the results back to codecov
after_success:
  - codecov