dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  # - pip install .
# command to run tests
script:
  - python manage.py makemigrations
  - python manage.py migrate --database=default
  - python manage.py migrate --database=messenger_users_db
  - python manage.py createsuperuser
  - python manage.py test -k
# Push the results back to codecov
after_success:
  - codecov